# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 19:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectedAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Plan name')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='price')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Connected account',
                'verbose_name_plural': 'Connected accounts',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CrawlsPerMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Plan name')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='price')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Crawl per month',
                'verbose_name_plural': 'Crawls per month',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NumberOfProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Plan name')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Price')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Number of product',
                'verbose_name_plural': 'Numbers of product',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Amount')),
                ('payment_date', models.DateTimeField(verbose_name='Payment date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment history',
                'verbose_name_plural': 'Payments history',
                'ordering': ['-payment_date'],
            },
        ),
    ]
